[package]
name = "lilium"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.1"
clap = { version = "4.5.40", features = ["derive"] }
pretty = "0.12.4"
thiserror = "2.0.12"
variadics_please = "1.1.0"
# strum = "0.27.1"
